[package]
name = "node"
version = "0.1.0"
authors = ["Raphael Matile <raphael.matile@gmail.com>"]

[dependencies]
bytes = "0.4.9"
env_logger = "0.5.12"
futures = "0.1.23"
libp2p = { git = "https://github.com/libp2p/rust-libp2p", rev = "486a9694d92b7107d29d8c7b663212211e75f4f2"}
tokio = "0.1"
tokio-codec = "0.1.0"
tokio-current-thread = "0.1.1"
